# Generated by Django 2.0 on 2023-07-03 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='check_in',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='check_out',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Check Out'),
        ),
    ]
