# Generated by Django 2.0 on 2023-07-07 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('ammount', models.CharField(max_length=100, verbose_name='Total Ammount')),
                ('note', models.TextField(max_length=100, verbose_name='Enter Note')),
                ('status', models.CharField(default='other', max_length=50, verbose_name='Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Enter Date')),
                ('attachment', models.ImageField(default=None, upload_to='', verbose_name='Image')),
            ],
        ),
    ]
