# Generated by Django 2.0 on 2023-07-07 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
                ('product', models.CharField(max_length=100, verbose_name='Product')),
                ('expenses_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expenses Date')),
                ('note', models.TextField(max_length=100, verbose_name='Note')),
                ('paid_by', models.CharField(default='other', max_length=20, verbose_name='Paid By')),
                ('image', models.ImageField(default=None, upload_to='', verbose_name='Image')),
            ],
        ),
    ]
