# Generated by Django 2.0 on 2023-07-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeModel',
            new_name='ExpenseModel',
        ),
    ]
