# Generated by Django 2.0 on 2023-07-07 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expenses', '0003_auto_20230707_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='image',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='expenses_date',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date'),
        ),
    ]
