# Generated by Django 2.0 on 2023-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expenses', '0004_auto_20230707_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='total_ammount',
            field=models.CharField(default=None, max_length=20, verbose_name='total_ammount'),
        ),
    ]
